---
- name:	install	ELK container 
  docker_container:
    name: elk
    image: sebp/elk
    log_driver:	syslog
    log_options:
      syslog-address: tcp://127.0.0.1:514
      syslog-facility: daemon
      tag: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "9300:9300"
      - "9600:9600"
    restart_policy: always
    state: started
    sysctls:
      vm.max_map_count: 262144
  when: ansible_facts ['hostname'] == "BlackWidow"

...
