---
- name: install python2 & python3
  hosts: all
  tasks:

    - name: install python2.7, python3.6, & python3-pip
      dnf:
        update_cache: true
        name: ['python27', 'python36', 'python3-pip']
        state: present
        install_weak_deps: true
      when:
        ansible_facts ['distribution'] != "CentOS"
        
...

